name: Deploy
on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrappers
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - run: ./gradlew publish
